"""phonenumbers added

Revision ID: 36cfff9084f3
Revises: fface104057d
Create Date: 2026-01-18 00:55:19.101304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cfff9084f3'
down_revision = 'fface104057d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_phone_number'), ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_phone_number'), type_='unique')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
