"""Added capacity fields to Transport and Accommodation models

Revision ID: fface104057d
Revises: 6f5cc1819517
Create Date: 2026-01-15 18:41:06.590615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fface104057d'
down_revision = '6f5cc1819517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))

    with op.batch_alter_table('transports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_capacity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transports', schema=None) as batch_op:
        batch_op.drop_column('total_capacity')

    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
